services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:4000/api

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=affiliatehub
      - DB_PASSWORD=affiliatehub_password
      - DB_NAME=affiliatehub
      - JWT_SECRET=your_jwt_secret_key_change_in_production
      - NODE_ENV=development
      - PORT=4000

  db:
    image: arm64v8/mysql:8.0
    ports:
      - "3307:3306"  # ポートを3307に変更
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=affiliatehub
      - MYSQL_USER=affiliatehub
      - MYSQL_PASSWORD=affiliatehub_password
    command: --default-authentication-plugin=mysql_native_password

  # Adminerのポートを8888に変更
  adminer:
    image: adminer:latest
    ports:
      - "8888:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on:
      - db

volumes:
  mysql_data: